# Generated by Django 4.1.7 on 2023-02-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_a', models.CharField(max_length=100)),
                ('column_b', models.CharField(max_length=100)),
            ],
        ),
    ]
